MelonRuntime/Melon

MelonJs.JavaScript/Bindings/Constructors/HttpResponse.js
MelonJs.JavaScript/Bindings/Tools/http.js
MelonJs.JavaScript/Containers/JintContainer.cs
MelonJs.JavaScript/Extensions/EngineExtensions.cs
MelonJs.JavaScript/MelonJs.JavaScript.csproj
MelonJs.JavaScript/Models/Web/MelonHttpResponse.cs
MelonJs.JavaScript/Tools/MelonHttp.cs
MelonJs.JavaScript/Tools/Output/MelonConsole.cs
MelonJs.JavaScript/Tools/Scripting/BindingReader.cs
MelonJs.JavaScript/Tools/Web/MelonHttp.cs

- http module with `request(target, method, body, headers)`
- support to http.request with get, post, patch, put and delete protocols

Feat: http module

---

MelonJs.JavaScript/Bindings/Tools/debug.js
MelonJs.JavaScript/Containers/JintContainer.cs
MelonJs.JavaScript/Extensions/EngineExtensions.cs
MelonJs.JavaScript/MelonJs.JavaScript.csproj

- Implemented optional stack tracing by using `debug.enableStackTracing(bool)`
- Implemented `debug` built-in module

Feat: Stack Tracing and debug module

---

MelonJS/Program.cs
MelonJs.Experiments/FileCrudApi/routes/deleteEntryRoute.js
MelonJs.Experiments/FileCrudApi/routes/getEntriesRoute.js
MelonJs.Experiments/FileCrudApi/routes/writeEntryRoute.js
MelonJs.JavaScript/Bindings/Tools/http.js
MelonJs.WebApps/WebApplicationManager.cs

Usage: `http.result(statusCode, response)`
To be used inside rest route functions

Feat: http.result function feature

---

README.md
com.cmd
projects/melon-runtime/Cli.NET/Cli.NET.csproj
projects/melon-runtime/Cli.NET/Tools/CommandContainer.cs
projects/melon-runtime/MelonJS/MelonJS.csproj
projects/melon-runtime/MelonJS/Program.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/console.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/debug.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/deep_clone.js
projects/melon-runtime/commands/melon.js
projects/melon-runtime/package-lock.json
projects/melon-runtime/package.json
scripts/windows/test.cmd

- Solved error to load `npx melon` command due to issues with commonjs modules
- Solved diverse issues with arguments loader

Fix/Chore: Detailed debug messages and package issues

---

projects/melon-runtime/MelonJs.JavaScript/Extensions/EngineExtensions.cs
projects/melon-runtime/MelonJs.Static/Tools/EngineManagement/EngineManager.cs
scripts/windows/run.cmd
scripts/windows/test.cmd

https://github.com/MelonRuntime/MelonJS/issues/29

Fix: fixed EngineExtensions and EngineManager to proper function of application.end()

---

README.md
projects/melon-runtime/MelonJS/Program.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/application.js
projects/melon-runtime/MelonJs.Models/Project/App.cs
projects/melon-runtime/package.json
projects/melon-types/lib/types/Tools/application.d.ts
projects/melon-types/package.json

- Implemented `application.baseDir()` function and types
- Fixed cache clear in `application.end()`
- Fixed default value app serialization issues from `app.json`
- Featuring Workers (documentation pendent)
- Now `load` function can load standalone functions (currently as strings) and expression functions and will parse other values correctly.
- Implemented built-in `PgClient` to connect to Postgres databases using raw sql directly
- Implemented `npx melon new` to generate MelonJS projects in the current folder + README
- Removed `std.sleep(ms: number)`

Feat: 1.1.0 implementations

---

projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/console.js
projects/melon-runtime/MelonJs.JavaScript/Extensions/EngineExtensions.cs
projects/melon-runtime/MelonJs.Static/Tools/Output/MelonConsole.cs

- `console.details(...arguments)`: displays information about the target objects, focused in debug

Feat: console.details

---

projects/melon-runtime/MelonJS/MelonJS.csproj
projects/melon-runtime/MelonJS/StaticData.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/console.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/debug.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/environment.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/std.js
projects/melon-runtime/MelonJs.JavaScript/Extensions/EngineExtensions.cs
projects/melon-runtime/MelonJs.Static/MelonProcess.cs
projects/melon-runtime/MelonJs.Static/Tools/Output/MelonConsole.cs
projects/melon-runtime/package.json
projects/melon-types/lib/types/Tools/debug.d.ts
projects/melon-types/lib/types/Tools/environment.d.ts
projects/melon-types/lib/types/Tools/std.d.ts
projects/melon-types/package.json

- Implemented `std.object` module with the functions `isTruthy`, `isFalsy`, `isEnumerable` and the submodule `string` with the method `putAt`
- Implemented `environment.process` module with the functions `getMemoryUsage`, `getPlatform`, `setTitle` and `getCurrentTime`
- Implemented function `debug.details`

Version: [runtime 1.4.0 stable] [types 1.5.0 stable]

---

projects/melon-runtime/commands/melon.js
projects/melon-runtime/package.json

chore: attempt to fix projectDirectory path in npx melon

---

projects/melon-runtime/MelonJS/MelonJS.csproj
projects/melon-runtime/MelonJS/StaticData.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Constructors/HttpApplication.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Constructors/HttpRoute.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/http.js
projects/melon-runtime/MelonJs.JavaScript/Extensions/EngineExtensions.cs
projects/melon-runtime/MelonJs.Models/Web/HttpApplication/HttpRoute.cs
projects/melon-runtime/MelonJs.Models/Web/HttpApplication/MelonHttpApplication.cs
projects/melon-runtime/MelonJs.WebApps/WebApplicationManager.cs
projects/melon-runtime/package.json
projects/melon-types/lib/types/Constructors/HttpApplication.d.ts
projects/melon-types/lib/types/Tools/http.d.ts
projects/melon-types/package.json

- http.app remake
- docker support updates

version: v1.5.0 implementations

---

CHANGELOG.md
projects/melon-runtime/MelonJS/MelonJS.csproj
projects/melon-runtime/MelonJS/StaticData.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Constructors/MPromise.js
projects/melon-runtime/MelonJs.JavaScript/Extensions/EngineExtensions.cs
projects/melon-runtime/MelonJs.JavaScript/MelonJs.JavaScript.csproj
projects/melon-runtime/package.json
projects/melon-types/lib/types/Constructors/Promise.d.ts
projects/melon-types/package.json

implementations: runtime@1.6.0-rc1 | types@1.8.0-rc2

---

projects/melon-types/lib/types/Tools/data.d.ts
projects/melon-types/package.json

+ implemented DatabaseClient type

hotfix: fixed database built in types [types v1.8.1]

---

projects/melon-runtime/MelonJS/MelonJS.csproj
projects/melon-runtime/MelonJS/StaticData.cs
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/http.js
projects/melon-runtime/MelonJs.WebApps/WebApplicationManager.cs
projects/melon-runtime/package.json
projects/melon-types/lib/types/Tools/http.d.ts
projects/melon-types/package.json

- Implemented http.static(string) and dynamic http responses with customized mime type
- Fixed http.result types and implemented new http.static type

implementations [runtime|1.7.0-next.1] [types|1.9.0-next.0]

---

README.md
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/environment.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/load.js
projects/melon-runtime/MelonJs.JavaScript/Bindings/Tools/std.js
projects/melon-types/lib/types/Tools/std.d.ts

fix: removed Replacement of a substring with itself in `load`
fix: remove Prototype-polluting assignment in `environment.getVariables`
fix: removed insecure `std.reflect` from internal library and types

Fix: Security issues #101 #100 #99

---

projects/melon-runtime/Melon.Library/Data/Enumerable.js
projects/melon-runtime/Melon.Library/Data/IndexedArray.js
projects/melon-runtime/Melon.Library/Melon.Library.csproj
projects/melon-runtime/Melon/Container.cs

- Information: related with bug #124

chore: implemented `Enumerable` and `IndexedArray` constructors

---

projects/melon-runtime/Melon/Commands/LoadCommand.cs
projects/melon-runtime/Melon/Commands/NewCommand.cs
projects/melon-runtime/Melon/Melon.csproj
projects/melon-runtime/Melon/Program.cs
projects/melon-runtime/package.json

- melon-runtime: `v1.7.2`
- melon-types `v1.9.1`
- 🎯 Hotfix Patch
- 🎯 **[core]** Refactored "NewCommand" ("new" command) class to consistently implement new project files in a scalable maneer
- 🎯 **[core]** Implemented execution handler in "run" and load "commands" to avoid program-breaking errors

Version: 1.7.2 [hotfixes/refactors in runtime]

---

README.md

- Shorter example that focuses on .NET interop
- Reword some sentences and headers for clarity

docs: Shorter and neater README

---

README.md
projects/melon-docs/Index.md
projects/melon-docs/MelonCommands.md
projects/melon-docs/modules/dotnet.md
projects/melon-types/dotnet.d.ts
projects/melon-types/types/dotnet/DotnetInstanceExpression.ts
projects/melon-types/types/dotnet/InteropResult.ts
projects/melon-types/types/dotnet/Realm.ts

- Markdown ocumentation implementations (in development)
- Minor `melon-types` miscellaneous fixes, refactors and implementations

Chore: documentation/types

---

utils/js.model.Dockerfile
utils/ts.model.Dockerfile

- Fixed and splitted docker configuration into js and ts dockerfiles, then updated to be compatible with latest Melon version

fix(utils): normalized docker configurations to js and ts

---

projects/melon-runtime/package.json

- Incorrect version compiled in 2.1.0

2.1.1: Compilation hotfix

---

projects/melon-runtime/Melon.Library/Static/InteropReflection/ReflectionHelper.cs

Co-Authored-By: Aaron Robinson <aaronrobin1234@gmail.com>
Co-Authored-By: Fred Silberberg <2371880+333fred@users.noreply.github.com>
Co-Authored-By: Mike Treit <8271812+Treit@users.noreply.github.com>

refactor: improved data types usage of ReflectionHelper

---

.gitignore
projects/melon-types/modules/Http/HttpTypes.ts

refactor: handles both upper and lowercase http method names

---

projects/melon-runtime/Melon.Tests/Melon.Tests.csproj
projects/melon-runtime/Melon.Tests/Melon/dotnet/DotnetThreadingTests.cs
projects/melon-runtime/Melon.Tests/Melon/http/HttpAppTests.cs
projects/melon-runtime/Melon.Web/Extensions/WebApplicationExtensions.cs

- Fixed a deserialization problem that was throwing errors in requests with body
- Solved multithreading problems in tests

Fix: Melon.http.app body deserialization problem

---

CONTRIBUTING.md
projects/melon-runtime/MelonRuntime.WebServices/Properties/Resources.resx

Fix: composed data/metadata in http requests generating 

---

projects/melon-runtime/MelonRuntime.CLI/Entities/MelonCLI.cs
projects/melon-runtime/MelonRuntime.CLI/MelonRuntime.CLI.csproj
projects/melon-runtime/MelonRuntime.Core/DependencyRunner.cs
projects/melon-runtime/MelonRuntime.Core/MelonRuntime.Core.csproj
projects/melon-runtime/package.json

- fix: removed help message after "new" command normal usage
- fix(deps-runner): added needed assemblies in order to run console internal functions

Feat(2.7.1): Misc major hotfixes in CLI and DependencyRunner
